"use client";

import { MessageSquareText, SendHorizontal } from "lucide-react";
import { FormEvent, useState } from "react";
import type { FinalIncidentPackage } from "@/lib/cerebras/schemas";
import {
  answerIncidentQuestion,
  defaultFollowUpQuestions,
  type EvidenceChatAnswer,
} from "@/lib/followup/evidence-chat";

type FollowUpChatProps = {
  result: FinalIncidentPackage;
};

export function FollowUpChat({ result }: FollowUpChatProps) {
  const [question, setQuestion] = useState("");
  const [answers, setAnswers] = useState<EvidenceChatAnswer[]>([]);

  function ask(value: string) {
    const answer = answerIncidentQuestion(result, value);
    setAnswers((current) => [answer, ...current].slice(0, 6));
    setQuestion("");
  }

  function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    ask(question);
  }

  return (
    <section className="grid gap-4">
      <div className="rounded border border-[#d6d1bf] bg-white p-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="flex items-center gap-2 text-lg font-semibold">
              <MessageSquareText size={18} aria-hidden="true" />
              Follow-up Evidence Chat
            </h2>
            <p className="mt-1 text-sm text-[#625d52]">
              Answers are generated by deterministic retrieval over the current
              incident package. No hidden AI response is used here.
            </p>
          </div>
        </div>

        <form onSubmit={onSubmit} className="mt-4 flex flex-col gap-2 sm:flex-row">
          <label className="sr-only" htmlFor="follow-up-question">
            Ask about incident evidence
          </label>
          <input
            id="follow-up-question"
            value={question}
            onChange={(event) => setQuestion(event.target.value)}
            placeholder="Ask about root cause, SQL checks, tests, release risk..."
            className="h-11 min-w-0 flex-1 rounded border border-[#d6d1bf] bg-[#fbfaf5] px-3 text-sm outline-none focus:border-[#116d6e]"
          />
          <button
            type="submit"
            className="inline-flex h-11 items-center justify-center gap-2 rounded border border-[#116d6e] bg-[#116d6e] px-4 text-sm font-semibold text-white hover:bg-[#0d5d5f]"
          >
            <SendHorizontal size={16} aria-hidden="true" />
            Ask
          </button>
        </form>

        <div className="mt-3 flex flex-wrap gap-2">
          {defaultFollowUpQuestions.map((suggestion) => (
            <button
              key={suggestion}
              type="button"
              onClick={() => ask(suggestion)}
              className="rounded border border-[#d6d1bf] bg-[#fbfaf5] px-3 py-2 text-xs font-semibold text-[#4f4a40] hover:border-[#116d6e]"
            >
              {suggestion}
            </button>
          ))}
        </div>
      </div>

      {answers.length === 0 ? (
        <div className="rounded border border-[#d6d1bf] bg-[#fbfaf5] p-4 text-sm text-[#625d52]">
          Ask a grounded follow-up question after the swarm returns an incident
          package. Unsupported questions show an explicit no-evidence response.
        </div>
      ) : (
        <div className="grid gap-3">
          {answers.map((answer) => (
            <article
              key={`${answer.question}-${answer.answer}`}
              className={`rounded border p-4 ${
                answer.ok
                  ? "border-[#b8d9d4] bg-[#effaf8]"
                  : "border-[#f0b89d] bg-[#fff4ed]"
              }`}
            >
              <p className="text-sm font-semibold text-[#161616]">
                {answer.question || "Empty question"}
              </p>
              <pre className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#4f4a40]">
                {answer.answer}
              </pre>
              {answer.sources.length > 0 ? (
                <div className="mt-4 grid gap-2">
                  {answer.sources.map((source) => (
                    <div
                      key={`${answer.question}-${source.label}-${source.score}`}
                      className="rounded border border-white/70 bg-white/70 p-3 text-xs text-[#4f4a40]"
                    >
                      <p className="font-semibold text-[#161616]">
                        {source.label} · score {source.score}
                      </p>
                      <p className="mt-1 leading-5">{source.excerpt}</p>
                    </div>
                  ))}
                </div>
              ) : null}
            </article>
          ))}
        </div>
      )}
    </section>
  );
}
